### ISSUE TITLE
ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by ranbuch** [juristr/webpack-typescript-starter#22]
I'm trying to deploy my project as a third party `npm module` with ES6 support.
When running `npm run build.prod` the `dist` folder contains only the `bundle.js` and `bundle.js.map` files.

After changing the `compilerOptions` in the `tsconfig.json` file by adding `"declaration": true` and `"allowJs": false,` and adding `"include": [
    "src/**/*"
  ]` to the file root I'm getting also `*.d.ts` files but the `*.ts` files are missing.

I've tried to add the `files` property and specify the exact files but the result is the same, no `*.ts` files are available on the `dist` folder.

When trying to use my `npm module` on another application with `npm install`ing it I'm getting the compilation error:
`my_module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`

How can I use this awesome boilerplate to create a third party module?

**Comment by juristr** [comment]
Hey, sorry for the late response. Unfortunately I'm no more using this starter because I didn't have the need to in some of the recent projects. I'm going to merge in ur PR, thx a lot for that 👏.

Other than that, you might also get some ideas from Alex Jover's setup of his TypeScript library starter: https://github.com/alexjoverm/typescript-library-starter
